blank_issues_enabled: true
contact_links:
  - name: BewCore Security Policy
    url: https://github.com/mraksoll4/bewcore/blob/master/SECURITY.md
    about: View security policy
  - name: BewCore Developers
    url: https://bewcore.org
    about: BewCore homepage
